void mode2(){
  int t=200;
  lcd.clear();
    lcd.setCursor(0, 0);
  lcd.print("Processing");
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    delay(1000);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("Processing");
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    delay(1000);
    password=random(1000,9999);
    lcd.clear();
    lcd.setCursor(0, 0);
    lcd.print("Processing");
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.setCursor(3, 1);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    lcd.print(".");
    delay(t);
    delay(1000);
    send_sms(password);
    lcd.clear();
    lcd.setCursor(2, 0);
    lcd.print("OTP has been");
    lcd.setCursor(6, 1);
    lcd.print("sent");
    mode=3;
    delay(3000);
    lcd.clear();
    

    
}
